import type { Metadata } from 'next'

import './globals.css'
import Footer from '@/layouts/footer/Footer'
import Header from '@/layouts/header/Header'
import { Noto_Sans_KR } from 'next/font/google'
import { headers } from 'next/headers'
import clsx from 'clsx'
import { detectDevice } from '@/utils/method'
import DeviceProvider from '@/contexts/DeviceProvider'
import AuthProvider from '@/contexts/AuthProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const notoSansKr = Noto_Sans_KR({
  // preload: true, 기본값
  subsets: ['latin'], // 또는 preload: false
  weight: ['100', '400', '700', '900'], // 가변 폰트가 아닌 경우, 사용할 fontWeight 배열
  display: 'swap',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const requestHeaders = headers()
  const userAgent = requestHeaders.get('user-agent')
  const deviceInfo = detectDevice(userAgent!)

  return (
    <html lang="en">
      <body className={clsx('flex flex-col bg-white', notoSansKr.className)}>
        <AuthProvider>
          <DeviceProvider deviceInfo={deviceInfo}>
            <Header />
            {children}
            <Footer />
          </DeviceProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
